### ISSUE TITLE
Xamarin.iOS / Xamarin.Android

### ISSUE THREAD

**Issue by Dismissile** [Azure-Samples/active-directory-xamarin-native-v2#2]
Does this library support Xamarin.iOS or just Xamarin.Forms?

I am trying to create a new instance of the PublicClientApplication class and I keep getting an exception:

'The type initializer for 'Microsoft.Identity.Client.Internal.PlatformPlugin' threw an exception.'

It looks like it is failing at:

   at Microsoft.Identity.Client.Internal.PlatformPlugin.LoadPlatformSpecificAssembly()
   at Microsoft.Identity.Client.Internal.PlatformPlugin.InitializeByAssemblyDynamicLinking()
   at Microsoft.Identity.Client.Internal.PlatformPlugin..cctor()

**Comment by jmprieur** [comment]
The library supports both Xamarin.IOS / Xamarin.Android native and Xamarin.Forms
this sample is for Xamarin form
